#!/bin/bash

echo "🔧 Google OAuth Configuration Fix for HomeHelp"
echo ""
echo "The Google Sign-In error occurs because redirect URIs are not configured."
echo ""
echo "📋 Follow these steps:"
echo ""
echo "1️⃣ Open Google Cloud Console Credentials:"
echo "   🔗 https://console.cloud.google.com/apis/credentials?project=recipebook-1a8d7"
echo ""
echo "2️⃣ Configure OAuth Consent Screen (if not done):"
echo "   • Go to OAuth consent screen"
echo "   • Select 'External' user type"
echo "   • App name: HomeHelp"
echo "   • Add scopes: email, profile"
echo "   • Save and continue"
echo ""
echo "3️⃣ Add Redirect URIs to iOS OAuth Client:"
echo "   • Click on client: 37849751232-j6jvm6uk4756i1mupooapp2isa7obg8q"
echo "   • Add these Authorized redirect URIs:"
echo ""
echo "   com.ashokjaiswal.home:/oauthredirect"
echo "   com.googleusercontent.apps.37849751232-j6jvm6uk4756i1mupooapp2isa7obg8q:/oauthredirect"
echo ""
echo "4️⃣ Add Redirect URIs to Web OAuth Client:"
echo "   • Click on client: 37849751232-vcktaqi606ra5rl52e1vkl3rslacbja5"
echo "   • Add these Authorized redirect URIs:"
echo ""
echo "   https://auth.expo.io/@ashokjaiswal/homehelp"
echo "   http://localhost:8081"
echo "   exp://localhost:8081"
echo ""
echo "   • Add these Authorized JavaScript origins:"
echo ""
echo "   http://localhost:8081"
echo "   http://localhost:19006"
echo ""
echo "5️⃣ Save all changes"
echo ""
echo "6️⃣ Restart Expo and test:"
echo "   npx expo start --ios --clear"
echo ""
echo "Opening Google Cloud Console..."
open "https://console.cloud.google.com/apis/credentials?project=recipebook-1a8d7"
echo ""
echo "✅ After configuration, Google Sign-In will work!"
